### ISSUE TITLE
ModuleNotFoundError: No module named 'biotite.structure.io.npz'

### ISSUE THREAD

**Issue by navvye** [evolutionaryscale/esm#96]
Everytime I try installing ESM on Google Colab, I run into a **ModuleNotFoundError: No module named 'biotite.structure.io.npz'.**

I tried installing biotite from source, but it's still throwing the error. 

Any suggestions?

**Comment by AlpriElse** [comment]
I'm unable to reproduce by creating a new Google Collab Notebook with Python 3.10.12 and running `!pip install esm` in a cell

Here's a gist of the successful output of running `pip install esm`
https://gist.github.com/AlpriElse/0ddd506d7ab933b41e31a4ae146f53fb

Can you provide more info like Python version or the full trace of what happens when you run `pip install esm`?

**Comment by ebetica** [comment]
Let me know if this is still an issue, I'm also unable to reproduce this.

**Comment by WrViajero** [comment]
For those who may encounter the same issue as me, i.e., biotite.structure.io.npz is not found, the issue can be quickly resolved by downgrading biotite version to 0.41.2 if not installed properly. Hope this update may help by running:

pip uninstall biotite
pip install biotite==0.41.2
